version: "{build}-{branch}"

branches:
  only:
    - master
    - dev-appveyor

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 25-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
